Repository geertmeersman/aiorobonect, pull requests merged in 2023-05, with the labels that each got.

#2 Cleanup
  aiorobonect/client.py
Labels: enhancement, patch

#3 async_cmds changed to dict
  aiorobonect/client.py
Labels: enhancement, patch

#7 Exceptions management
  aiorobonect/client.py
Labels: enhancement, patch

#8 Exceptions management
  aiorobonect/client.py
Labels: patch, fix

#9 Exceptions management
  aiorobonect/client.py
Labels: enhancement, patch

#11 Session closure
  aiorobonect/client.py
Labels: enhancement, patch

#12 JSON validator
  aiorobonect/client.py
Labels: enhancement, patch

#13 JSON UTF-8 encoding forced
  aiorobonect/client.py
Labels: enhancement, patch

#14 aiohttp response to utf-8
  aiorobonect/client.py
Labels: enhancement, patch

#15 fix: iso-8859-1 encoding for json answers
  aiorobonect/client.py
Labels: patch, fix

#17 PR Checker
  .github/scripts/pr_extract_labels.py
  .github/workflows/pr-checker.yml
  .pre-commit-config.yaml
Labels: enhancement, patch

#18 feat: pr checker
  .github/labels.yml
  .github/scripts/pr_extract_labels.py
  .github/workflows/pr-checker.yml
  COMMIT_MESSAGES
Labels: minor, fix, feat

#16 Use ISO-8859-15 as it fully includes French and other language compatibility
  aiorobonect/client.py
Labels: patch, fix
